Process data
bizip/my-blog pull request #2
Opened 2022-08-17 13:53 UTC by bizip

**What does this PR do?**

- Users

A method that returns the 3 most recent posts for a given user.

- Posts

A method that updates the posts counter for a user.
A method that returns the 5 most recent comments for a given post.

- Comments

A method that updates the comments counter for a post.

- Likes

A method that updates the likes counter for a post.

- All columns that are foreign keys should have a corresponding index.

**Description of Task to be completed**

All tasks are completed 

**How should this be manually tested?**

1. Clone this repository and switch to `process-data`

2022-08-17 14:17 UTC, rloterh requested changes
Hi Pascal, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Descriptive commit messages


## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 14:17 UTC, rloterh commented on app/models/user.rb
> +  has_many :comments
- [ ] As per the given _ERD_, the _User_ **association** should have _author_id_ referenced as **foreign key** in _Post_, _Comment,_ and _Like_ models. Kindly ensure to improve this aspect, similar to the code example below:
```ruby
has_many :posts, foreign_key: 'author_id'
has_many :comments, foreign_key: 'author_id'
has_many :likes, foreign_key: 'author_id'
```

2022-08-17 14:17 UTC, rloterh commented on app/models/post.rb
> +  belongs_to :user
- [ ] As per the given _ERD_, the _Post_ **association** should have _Post_ belong to _User_ **through** _Author_, an alias of _User_, like below:
`belongs_to :author, class_name: 'User'` 

    Kindly ensure to improve upon this aspect.

2022-08-17 14:17 UTC, rloterh commented on app/models/comment.rb
> +  belongs_to :user
- [ ] As per the given _ERD_, the _Comment_ **association** should have _Comment_ belong to _User_ **through** _Author_, an alias of _User_, like below:
`belongs_to :author, class_name: 'User'`

2022-08-17 14:17 UTC, rloterh commented on app/models/like.rb
> +  belongs_to :user
- [ ] As per the given _ERD_, the _Like_ **association** should have _Like_ belong to _User_ **through** _Author_, an alias of _User_, like below:
`belongs_to :author, class_name: 'User'` 

    Kindly ensure to improve upon this aspect.

2022-08-17 14:17 UTC, rloterh commented on app/models/post.rb
> +  end
- [ ] OPTIONAL
It is a nice idea to use one of the Rails Active Callbacks `after_save` to call the `update_posts_counter` method every time a new post has been saved to database, then make the `update_posts_counter` method private, similar to:

```ruby
 # app/models/post.rb
  after_save :update_post_counter

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
```

2022-08-17 14:17 UTC, rloterh commented on app/models/comment.rb
> +  end
- [ ] OPTIONAL
It is a nice idea to use one of the Rails Active Callbacks `after_save` to call the `update_comments_counter method every time a new like has been saved to database, then make the `update_comments_counter` method private, similar to:

```ruby
 # app/models/comments.rb
  after_save :update_comments_counter

  private

  def update_comment_counter
    author.increment!(:comments_counter)
  end
```

2022-08-17 14:17 UTC, rloterh commented on app/models/like.rb
> +  end
- [ ] OPTIONAL
It is a nice idea to use one of the Rails Active Callbacks `after_save` to call the `update_likes_counter method every time a new like has been saved to database, then make the `update_likes_counter` method private, similar to:

```ruby
 # app/models/likes.rb
  after_save :update_like_counter

  private

  def update_like_counter
    author.increment!(:likes_counter)
  end
```

2022-08-18 07:05 UTC, AshakaE approved these changes
Hi @bizip 🙋‍♂️,

Code looks good 👍

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 07:10 UTC, merged